added CountryCurrency
ipinfo/csharp pull request #17
Opened 2022-11-16 08:29 UTC by rm-Umar

2022-11-16 09:01 UTC, UmanShahzad approved these changes
@SobanMahmood please also do check.

2022-11-17 10:44 UTC, rm-Umar commented
I've added `Continent` in this PR as well. 
cc: @UmanShahzad @SobanMahmood

2022-11-24 06:51 UTC, SobanMahmood requested changes
Looks good to me, just minor updates in comments/readme.

2022-11-24 06:51 UTC, SobanMahmood commented on src/IPinfo/Models/Continent.cs
> +  /// { "code": "PKR" ,"name": "Asia"}
```suggestion
  /// { "code": "AS", "name": "Asia"}
```

2022-11-24 06:51 UTC, SobanMahmood commented on README.md
> +// continent name , e.g. "US" -> "North America"
```suggestion
// continent name, e.g. "US" -> "North America"
```

2022-11-24 07:03 UTC, rm-Umar commented
If everything seems good we can merge it.
@UmanShahzad @SobanMahmood

2022-11-24 07:08 UTC, SobanMahmood approved these changes

2022-11-24 07:12 UTC, merged